services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=fitnessapp'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    restart: no

volumes:
  postgres_data: